apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-server
  labels:
    service: {{ .Chart.Name }}-server
spec:
  replicas: 3
  selector:
    matchLabels:
      service: {{ .Chart.Name }}-server
  template:
    metadata:
      labels:
        service: {{ .Chart.Name }}-server
    spec:
      containers:
      - name: web-server
        image: {{ tuple "werf-web" . | werf_image }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: HOSTNAME
          value: {{ .Values.server.hostname }}
        - name: USER
          value: {{ .Values.server.user }}   
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-server
spec:
  clusterIP: None
  selector:
    service: {{ .Chart.Name }}-server
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
