#Test
name: Staging Deployment
on:
  push:
    branches: [deploy]
jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install werf CLI  
        uses: werf/actions/install@master
        
      - name: Run werf commands
        run: |
          werf helm repo init
          werf helm dependency build
      
      - name: Converge
        uses: werf/actions/converge@master
        with:
          env: staging
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
          
      - name: Dismiss if failed
        if: ${{ failure() }}
        uses: werf/actions/dismiss@master
        with:
          env: staging
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
